# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-01-29 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
